server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/obaid305/labfinal
          default-label: main

  security:
    user:
      name: configuser
      password: configpass
